#include "ui/RigUi.h"
#include <cstdio>
#include <cstring>
#include "RigBuildConfig.h"
#include "ui/UiTheme.h"
namespace rig {
namespace {
const char* const kNames[]={"STATUS","NETWORK","DEVICE","CONTROLS"};
const char* const kStatus[]={"RETRY FAILED STAGE","REFRESH API","CLEAR LAST ERROR","RETURN TO SUMMARY"};
const char* const kNetwork[]={"RETRY NOW","SCAN NETWORKS","SELECT SSID","EDIT SSID","EDIT PASSWORD","EDIT API URL","TEST API","DISCONNECT","FORGET WIFI"};
const char* const kDevice[]={"EDIT NODE ID","EDIT DEVICE TOKEN","EDIT API URL","RELOAD SD CONFIG","CLEAR SAVED OVERRIDES","DISPLAY TEST","TOUCH TEST","REBOOT DEVICE"};
const char* const kControls[]={"POLL SESSION","START RECORDING","STOP RECORDING","ACKNOWLEDGE ERROR","RETURN TO STATUS"};
uint32_t elapsed(uint32_t now,uint32_t then){return now-then;}
}
void RigUi::begin(const RigSnapshot&s){snapshot_=s;const uint32_t before=ESP.getFreeHeap();bool ok=compositor_.begin();const uint32_t after=ESP.getFreeHeap();counters_.minFreeHeap=after;Serial.printf("ui: indexed compositor=%s bytes=%lu heap=%lu->%lu\n",ok?"ready":"span-fallback",(unsigned long)compositor_.allocationBytes(),(unsigned long)before,(unsigned long)after);display_.gfx().fillScreen(theme::kBlack);halo_.begin(s.state);invalidation_.add(BackgroundDirty|HeaderDirty|SummaryBodyDirty);}
bool RigUi::visibleSnapshotChanged(const RigSnapshot&s)const{if(s.state!=snapshot_.state||s.retrySeconds!=snapshot_.retrySeconds||s.wifiConnected!=snapshot_.wifiConnected||s.sessionPresent!=snapshot_.sessionPresent||s.configParsed!=snapshot_.configParsed||s.sdReady!=snapshot_.sdReady||s.nvsOverrides!=snapshot_.nvsOverrides||s.tokenConfigured!=snapshot_.tokenConfigured)return true;if(expanded()&&(s.requestInProgress!=snapshot_.requestInProgress||strcmp(s.lastError,snapshot_.lastError)||strcmp(s.sessionStatus,snapshot_.sessionStatus)||strcmp(s.ipAddress,snapshot_.ipAddress)))return true;return false;}
void RigUi::updateSnapshot(const RigSnapshot&s){const bool changed=visibleSnapshotChanged(s);RigState old=snapshot_.state;snapshot_=s;if(old!=s.state)halo_.setState(s.state);if(changed)invalidation_.add(expanded()?RowDirty:SummaryBodyDirty);}
bool RigUi::expanded()const{return mode_!=UiMode::Summary&&mode_!=UiMode::TabHolding;}
void RigUi::tick(uint32_t now){if(!lastTickUs_)lastTickUs_=now;uint32_t delta=now-lastTickUs_;lastTickUs_=now;if(mode_==UiMode::Scrolling||scroll_.moving()){scroll_.tick(delta/1000000.0f);invalidation_.add(ScrollDirty);}if(mode_==UiMode::Expanding||mode_==UiMode::Collapsing){uint32_t duration=mode_==UiMode::Expanding?260000:200000;transitionProgress_=static_cast<uint16_t>(min(1000UL,elapsed(now,animationAtUs_)*1000UL/duration));invalidation_.add(PanelViewportDirty);if(transitionProgress_>=1000){mode_=mode_==UiMode::Expanding?UiMode::Expanded:UiMode::Summary;invalidation_.add(BackgroundDirty|HeaderDirty|(mode_==UiMode::Summary?SummaryBodyDirty:PanelViewportDirty));}}
 if(contact_){uint32_t held=elapsed(now/1000,pressAtMs_);halo_.setTouchFeedback(true,touchX_,touchY_,min(1000UL,held*1000UL/450UL),dragged_);invalidation_.add(FeedbackDirty);}else halo_.setTouchFeedback(false,0,0,0,false);
 uint16_t dirty=invalidation_.take();if(dirty)compose(dirty);halo_.setInteractive(expanded());halo_.tick(now);counters_.minFreeHeap=min(counters_.minFreeHeap,ESP.getFreeHeap());if(elapsed(now,lastDiagnosticUs_)>=5000000){lastDiagnosticUs_=now;Serial.printf("ui: full=%lu viewport=%lu rows=%lu feedback=%lu compose=%luus transfer=%luus touchmax=%lums heapmin=%lu\n",(unsigned long)counters_.fullRedraws,(unsigned long)counters_.viewportRedraws,(unsigned long)counters_.rowRedraws,(unsigned long)counters_.feedbackRedraws,(unsigned long)counters_.composeUs,(unsigned long)counters_.transferUs,(unsigned long)counters_.maxTouchIntervalMs,(unsigned long)counters_.minFreeHeap);}}
void RigUi::handleTouch(const TouchEvent&e){if(e.kind==TouchKind::None)return;if(lastTickUs_){uint32_t gap=e.timestampMs-(lastTickUs_/1000);counters_.maxTouchIntervalMs=max(counters_.maxTouchIntervalMs,gap);}touchX_=e.x;touchY_=e.y;
 if(e.kind==TouchKind::PressStarted){contact_=true;dragged_=false;pressAtMs_=e.timestampMs;pressedRow_=expanded()?actionAt(e.x,e.y):-1;invalidation_.add(FeedbackDirty);return;}if(e.kind==TouchKind::DragStarted||e.kind==TouchKind::DragMoved){dragged_=true;pressedRow_=-1;invalidation_.add(FeedbackDirty);}
 if(e.zone==TouchZone::Center&&e.kind==TouchKind::HoldStarted){contact_=false;showStatus();return;}if(mode_==UiMode::Keyboard){if(e.kind==TouchKind::SwipeDown){contact_=false;mode_=modalReturnMode_;invalidation_.add(BackgroundDirty|PanelViewportDirty);}else if(e.kind==TouchKind::Tap&&!dragged_){appendKey(keyboardKeyAt(e.x,e.y));contact_=false;}else if(e.kind==TouchKind::Cancelled||e.kind==TouchKind::Released)contact_=false;return;}
 if(mode_==UiMode::Confirm){if(e.kind==TouchKind::SwipeDown){mode_=modalReturnMode_;contact_=false;invalidation_.add(OverlayDirty);}else if(e.kind==TouchKind::Tap&&!dragged_&&e.y>=158){if(e.x<120)mode_=modalReturnMode_;else if(page_==UiPage::Network)queue(UiAction::ForgetWifi);else if(confirmRow_==4)queue(UiAction::ClearOverrides);else queue(UiAction::Reboot);contact_=false;invalidation_.add(OverlayDirty);}return;}
 if(mode_==UiMode::Summary||mode_==UiMode::TabHolding){if(e.kind==TouchKind::SwipeLeft){changePage(1);contact_=false;}else if(e.kind==TouchKind::SwipeRight){changePage(-1);contact_=false;}else if(e.kind==TouchKind::SwipeUp||e.kind==TouchKind::HoldStarted){contact_=false;expand();}else if(e.kind==TouchKind::Tap&&!dragged_){contact_=false;if(e.y>=18&&e.y<=55)expand();else cyclePage();}else if(e.kind==TouchKind::Cancelled||e.kind==TouchKind::Released){contact_=false;invalidation_.add(FeedbackDirty);}return;}
 if(e.kind==TouchKind::Tap&&!dragged_&&e.y<48){contact_=false;collapse();return;}if(e.kind==TouchKind::DragStarted){scroll_.beginDrag();mode_=UiMode::Scrolling;}else if(e.kind==TouchKind::DragMoved){scroll_.drag(e.deltaY);invalidation_.add(ScrollDirty);}else if(e.kind==TouchKind::SwipeDown&&scroll_.offset()<=0){contact_=false;collapse();}else if(e.kind==TouchKind::SwipeUp){scroll_.release(e.velocityY);mode_=UiMode::Expanded;contact_=false;}else if(e.kind==TouchKind::Released&&mode_==UiMode::Scrolling){contact_=false;if(scroll_.shouldCollapse())collapse();else{scroll_.release(e.velocityY);mode_=UiMode::Expanded;}}else if(e.kind==TouchKind::Tap&&!dragged_){int row=actionAt(e.x,e.y);contact_=false;if(row>=0)executeRow(row);}else if(e.kind==TouchKind::Cancelled){contact_=false;invalidation_.add(FeedbackDirty);}}
void RigUi::compose(uint16_t dirty){
 uint32_t start=micros();Arduino_GFX&g=compositor_.ready()?compositor_.canvas():display_.gfx();
 const bool rebuild=(dirty&(BackgroundDirty|HeaderDirty|SummaryBodyDirty|PanelViewportDirty|RowDirty|ScrollDirty|OverlayDirty|FeedbackDirty))!=0;
 if(rebuild){if(compositor_.ready())compositor_.clear(expandedView_,theme::kBlack);else for(int y=0;y<240;y++){auto span=expandedView_.span(y);if(span.valid())g.drawFastHLine(span.left,y,span.width(),theme::kBlack);}
  if(mode_==UiMode::Summary)drawSummary(g);else if(mode_==UiMode::Keyboard)drawKeyboard(g);else if(mode_==UiMode::Confirm)drawConfirm(g);else drawPanel(g);if(contact_)drawFeedback(g);
  if(dirty&(BackgroundDirty|SummaryBodyDirty))counters_.fullRedraws++;else if(dirty&RowDirty)counters_.rowRedraws++;else if(dirty&FeedbackDirty)counters_.feedbackRedraws++;else counters_.viewportRedraws++;}
 counters_.composeUs=micros()-start;if(compositor_.ready()){start=micros();compositor_.present(expandedView_);counters_.transferUs=micros()-start;}
}
void RigUi::drawSummary(Arduino_GFX&g){text(g,pageName(),120,25,2,theme::kWhite,true);separator(g,47,accent());text(g,stateLabel(),120,75,3,accent(),true);char secondary[64],diagnostic[72];if(page_==UiPage::Status){snprintf(secondary,sizeof(secondary),"%.40s",snapshot_.detail);snprintf(diagnostic,sizeof(diagnostic),"WIFI %s  RETRY %us",snapshot_.wifiConnected?"READY":"UNAVAILABLE",snapshot_.retrySeconds);}else if(page_==UiPage::Network){snprintf(secondary,sizeof(secondary),"%.32s",snapshot_.wifiSsid[0]?snapshot_.wifiSsid:"SSID NOT SET");snprintf(diagnostic,sizeof(diagnostic),"%s  %s",wifiStageLabel(snapshot_.wifiStage),snapshot_.wifiReasonText);}else if(page_==UiPage::Device){snprintf(secondary,sizeof(secondary),"XIAO C3");snprintf(diagnostic,sizeof(diagnostic),"SD %s CFG %s NVS %s TOKEN %s",snapshot_.sdReady?"OK":"--",snapshot_.configParsed?"OK":"BAD",snapshot_.nvsOverrides?"YES":"NO",snapshot_.tokenConfigured?"SET":"--");}else{snprintf(secondary,sizeof(secondary),"%s",snapshot_.sessionPresent?"LIVE SESSION":"NO SESSION");snprintf(diagnostic,sizeof(diagnostic),"TAP TITLE OR SWIPE UP");}text(g,secondary,120,126,1,theme::kWhite,true);text(g,diagnostic,120,158,1,theme::kMuted,true);}
void RigUi::drawPanel(Arduino_GFX&g){char header[24];snprintf(header,sizeof(header),"< %s",pageName());text(g,header,120,16,1,theme::kWhite,true);separator(g,39,accent());const char*const*rows=page_==UiPage::Status?kStatus:page_==UiPage::Network?kNetwork:page_==UiPage::Device?kDevice:kControls;int count=page_==UiPage::Status?4:page_==UiPage::Network?9:page_==UiPage::Device?8:5;int rowHeight=30;for(int i=0;i<count;i++){int y=52+i*rowHeight-static_cast<int>(scroll_.offset());if(mode_==UiMode::Expanding)y+=(1000-transitionProgress_)*90/1000;else if(mode_==UiMode::Collapsing)y+=transitionProgress_*90/1000;if(y<-10||y>225)continue;bool disabled=page_==UiPage::Help&&((i==1&&(!snapshot_.sessionPresent||!snapshot_.tokenConfigured||snapshot_.state==RigState::Recording||snapshot_.requestInProgress))||(i==2&&(!snapshot_.sessionPresent||!snapshot_.tokenConfigured||snapshot_.state!=RigState::Recording||snapshot_.requestInProgress)));auto span=expandedView_.span(y+8);if(!span.valid())continue;uint16_t color=disabled?theme::kMuted:(page_==UiPage::Device&&(i==4||i==7)||page_==UiPage::Network&&i==8)?theme::kAmber:theme::kWhite;g.fillCircle(span.left+7,y+7,2,(pressedRow_==i&&contact_)?theme::kWhite:accent());text(g,rows[i],span.left+15,y+2,1,color,false);if(disabled){const char*reason=!snapshot_.sessionPresent?"NO LIVE SESSION":!snapshot_.tokenConfigured?"TOKEN REQUIRED":snapshot_.requestInProgress?"REQUEST IN PROGRESS":i==1?"ALREADY RECORDING":"NOT RECORDING";text(g,reason,span.left+15,y+13,1,theme::kMuted,false);}separator(g,y+26,theme::kPanel);}}
void RigUi::drawKeyboard(Arduino_GFX&g){text(g,"< EDIT",120,12,1,theme::kWhite,true);char shown[29];if(masked_&&!reveal_){size_t n=min(strlen(edit_),sizeof(shown)-1);memset(shown,'*',n);shown[n]=0;}else snprintf(shown,sizeof(shown),"%.28s",edit_);text(g,shown,120,33,1,theme::kWhite,true);static const char lower[]="abcdefghijklmnopqrstuvwx";static const char upper[]="ABCDEFGHIJKLMNOPQRSTUVWX";static const char symbol[]="1234567890-_=+./:?@#$%^&";const char*keys=layout_==0?lower:layout_==1?upper:symbol;for(int i=0;i<24;i++){int row=i/6,y=58+row*31;auto span=expandedView_.span(y+10);int cell=max(24,span.width()/6);int x=span.left+(i%6)*cell+cell/2;char label[2]={keys[i],0};text(g,label,x,y,1,theme::kWhite,true);}text(g,"BKSP SPACE CLEAR",120,184,1,theme::kMuted,true);text(g,layout_==0?"ABC  123  SHOW  OK":"abc  123  SHOW  OK",120,205,1,accent(),true);}
void RigUi::drawConfirm(Arduino_GFX&g){drawPanel(g);for(int y=45;y<220;y+=3){auto s=expandedView_.span(y);if(s.valid())for(int x=s.left;x<=s.right;x+=4)g.drawPixel(x,y,theme::kBlack);}text(g,"CONFIRM",120,72,2,theme::kAmber,true);text(g,"THIS CANNOT BE UNDONE",120,112,1,theme::kWhite,true);text(g,"CANCEL",70,169,1,theme::kGreen,true);text(g,"CONFIRM",169,169,1,theme::kRed,true);}
void RigUi::drawFeedback(Arduino_GFX&g){if(!contact_)return;if(mode_==UiMode::Summary&&touchY_<65)separator(g,48,theme::kWhite);else if(pressedRow_>=0){int y=52+pressedRow_*30-static_cast<int>(scroll_.offset());auto s=expandedView_.span(y+10);if(s.valid())g.drawFastHLine(s.left+5,y+25,max(0,s.width()-10),accent());}}
void RigUi::text(Arduino_GFX&g,const char*t,int x,int y,uint8_t size,uint16_t color,bool centered){if(!t)return;auto span=(mode_==UiMode::Summary?summaryView_:expandedView_).span(y+size*4);if(!span.valid())return;char clipped[48];snprintf(clipped,sizeof(clipped),"%.47s",t);int maxChars=max(1,span.width()/(6*size));if((int)strlen(clipped)>maxChars)clipped[maxChars]=0;g.setTextSize(size);g.setTextColor(color);if(centered){int16_t x1,y1;uint16_t w,h;g.getTextBounds(clipped,0,y,&x1,&y1,&w,&h);{int centeredX=(240-static_cast<int>(w))/2-x1;x=centeredX<span.left?span.left:centeredX;}}else x=x<span.left?span.left:x;g.setCursor(x,y);g.print(clipped);}
void RigUi::separator(Arduino_GFX&g,int y,uint16_t color){auto s=(mode_==UiMode::Summary?summaryView_:expandedView_).span(y);if(s.valid())g.drawFastHLine(s.left+8,y,max(0,s.width()-16),color);}
int RigUi::actionAt(uint16_t x,uint16_t y)const{if(!expandedView_.contains(x,y)||y<45)return-1;int count=page_==UiPage::Status?4:page_==UiPage::Network?9:page_==UiPage::Device?8:5;return scroll_.rowAt(y,52,30,count);}
int RigUi::keyboardKeyAt(uint16_t x,uint16_t y)const{if(!expandedView_.contains(x,y))return-1;if(y>=58&&y<182){auto s=expandedView_.span(y);if(!s.valid())return-1;int row=(y-58)/31,col=(x-s.left)*6/max(1,s.width());return row<4&&col>=0&&col<6?row*6+col:-1;}if(y>=182&&y<202)return x<80?24:x<160?25:26;if(y>=202)return x<60?27:x<115?27:x<175?28:29;return-1;}
void RigUi::appendKey(int key){static const char lower[]="abcdefghijklmnopqrstuvwx",upper[]="ABCDEFGHIJKLMNOPQRSTUVWX",symbols[]="1234567890-_=+./:?@#$%^&";if(key>=0&&key<24){const char*m=layout_==0?lower:layout_==1?upper:symbols;size_t n=strlen(edit_);if(n<sizeof(edit_)-1){edit_[n]=m[key];edit_[n+1]=0;}}else if(key==24){size_t n=strlen(edit_);if(n)edit_[n-1]=0;}else if(key==25){size_t n=strlen(edit_);if(n<sizeof(edit_)-1){edit_[n]=' ';edit_[n+1]=0;}}else if(key==26)edit_[0]=0;else if(key==27)layout_=(layout_+1)%3;else if(key==28)reveal_=!reveal_;else if(key==29){command_={};command_.action=UiAction::SaveConfig;command_.field=editField_;strncpy(command_.value,edit_,sizeof(command_.value)-1);commandReady_=true;mode_=modalReturnMode_;}invalidation_.add(OverlayDirty);}
void RigUi::openEditor(ConfigField f,const char*v,bool mask){editField_=f;strncpy(edit_,v?v:"",sizeof(edit_)-1);edit_[sizeof(edit_)-1]=0;masked_=mask;reveal_=false;layout_=0;modalReturnMode_=UiMode::Expanded;mode_=UiMode::Keyboard;invalidation_.add(BackgroundDirty|OverlayDirty);}
void RigUi::executeRow(int r){if(page_==UiPage::Status){if(r==0)queue(UiAction::RetryWifi);else if(r==1)queue(UiAction::PollApi);else if(r==2)queue(UiAction::ClearError);else if(r==3)collapse();}else if(page_==UiPage::Network){if(r==0)queue(UiAction::RetryWifi);else if(r==1)queue(UiAction::ScanWifi);else if(r==2)queue(UiAction::SelectWifi);else if(r==3)openEditor(ConfigField::WifiSsid,snapshot_.wifiSsid,false);else if(r==4)openEditor(ConfigField::WifiPassword,"",true);else if(r==5)openEditor(ConfigField::ApiBase,snapshot_.apiBase,false);else if(r==6)queue(UiAction::TestApi);else if(r==7)queue(UiAction::DisconnectWifi);else if(r==8){confirmRow_=r;modalReturnMode_=UiMode::Expanded;mode_=UiMode::Confirm;invalidation_.add(OverlayDirty);}}else if(page_==UiPage::Device){if(r==0)openEditor(ConfigField::NodeId,snapshot_.nodeId,false);else if(r==1)openEditor(ConfigField::BearerToken,"",true);else if(r==2)openEditor(ConfigField::ApiBase,snapshot_.apiBase,false);else if(r==3)queue(UiAction::ReloadSd);else if(r==4||r==7){confirmRow_=r;modalReturnMode_=UiMode::Expanded;mode_=UiMode::Confirm;invalidation_.add(OverlayDirty);}else if(r==5)queue(UiAction::DisplayTest);else if(r==6)queue(UiAction::TouchTest);}else{bool startOk=r==1&&snapshot_.sessionPresent&&snapshot_.tokenConfigured&&snapshot_.state!=RigState::Recording&&!snapshot_.requestInProgress;bool stopOk=r==2&&snapshot_.sessionPresent&&snapshot_.tokenConfigured&&snapshot_.state==RigState::Recording&&!snapshot_.requestInProgress;if(r==0)queue(UiAction::PollApi);else if(startOk)queue(UiAction::StartRecording);else if(stopOk)queue(UiAction::StopRecording);else if(r==3)queue(UiAction::ClearError);else if(r==4)showStatus();else{halo_.setOutcomeFeedback(false);invalidation_.add(FeedbackDirty);}}}
void RigUi::expand(){mode_=UiMode::Expanding;animationAtUs_=micros();transitionProgress_=0;int count=page_==UiPage::Status?4:page_==UiPage::Network?9:page_==UiPage::Device?8:5;scroll_.configure(166,count*30);invalidation_.add(BackgroundDirty|PanelViewportDirty);}
void RigUi::collapse(){mode_=UiMode::Collapsing;animationAtUs_=micros();transitionProgress_=0;invalidation_.add(BackgroundDirty|PanelViewportDirty);}
void RigUi::changePage(int direction){int p=(static_cast<int>(page_)+direction+4)%4;page_=static_cast<UiPage>(p);animationAtUs_=micros();invalidation_.add(BackgroundDirty|HeaderDirty|SummaryBodyDirty);}
void RigUi::cyclePage(){changePage(1);}void RigUi::showStatus(){page_=UiPage::Status;mode_=UiMode::Summary;contact_=false;scroll_.configure(1,1);invalidation_.add(BackgroundDirty|HeaderDirty|SummaryBodyDirty|OverlayDirty);}void RigUi::queue(UiAction a){command_={};command_.action=a;commandReady_=true;}bool RigUi::takeCommand(UiCommand&c){if(!commandReady_)return false;c=command_;commandReady_=false;return true;}
const char*RigUi::pageName()const{return kNames[static_cast<int>(page_)];}const char*RigUi::stateLabel()const{switch(snapshot_.state){case RigState::Booting:return"BOOT";case RigState::WifiConnecting:return"JOINING";case RigState::WifiOffline:return"OFFLINE";case RigState::ApiOffline:return"API OFFLINE";case RigState::NoSession:return"RIG READY";case RigState::Previewing:return"STANDBY";case RigState::Recording:return"REC";case RigState::Sending:return"SENDING";case RigState::Error:return"ERROR";}return"UNKNOWN";}uint16_t RigUi::accent()const{if(snapshot_.state==RigState::Error||snapshot_.state==RigState::Recording)return theme::kRed;if(snapshot_.state==RigState::NoSession||snapshot_.state==RigState::Previewing)return theme::kGreen;return page_==UiPage::Help?theme::kViolet:page_==UiPage::Device?theme::kCyan:theme::kAmber;}
}
